server:
  port: 8031
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/platform-core?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
  redis:
    host: 192.168.99.100
    password:
security:
  oauth2:
    client:
      client_id: app
      client_secret: app
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /user/info/**
    resource:
      token-info-uri: http://localhost:3000/auth/oauth/check_token
      jwt:
        #         key-uri: http://localhost:3000/auth/oauth/token_key
        key-value: platform-key