server:
  port: 8031
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform-core?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
  redis:
    host: localhost
    password: