routes:
  - id: upms
    uri: lb://cleanarch-infrastructure-upms
    predicates:
      - Path=/auth/**,/upms/**
  - id: camunda
    uri: lb://cleanarch-infrastructure-camunda
    predicates:
      - Path=/camunda/**
  - id: codegen
    uri: lb://cleanarch-infrastructure-codegen
    predicates:
      - Path=/codegen/**
  - id: demo
    uri: lb://cleanarch-business-demo
    predicates:
      - Path=/demo/**
  - id: ssoclient1
    uri: lb://cleanarch-business-ssoclient1
    predicates:
      - Path=/ssoclient1/**
  - id: ssoclient2
    uri: lb://cleanarch-business-ssoclient2
    predicates:
      - Path=/ssoclient2/**