spring:
  cloud:
    gateway:
      default-filters:
      routes:
        - id: auth
          uri: lb://cleanarch-business-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: codegen
          uri: lb://cleanarch-business-codegen
          predicates:
            - Path=/codegen/**
          filters:
            - StripPrefix=1
        - id: demo
          uri: lb://cleanarch-business-demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        - id: ssoclient1
          uri: lb://cleanarch-business-ssoclient1
          predicates:
            - Path=/ssoclient1/**
          filters:
            - StripPrefix=1
        - id: ssoclient2
          uri: lb://cleanarch-business-ssoclient2
          predicates:
            - Path=/ssoclient2/**
          filters:
            - StripPrefix=1