routes:
  - id: upms
    uri: lb://cleanarch-infrastructure-upms
    predicates:
      - Path=/upms/**
  - id: camunda
    uri: lb://cleanarch-infrastructure-camunda
    predicates:
      - Path=/camunda/**
  - id: tools
    uri: lb://cleanarch-infrastructure-tools
    predicates:
      - Path=/tools/**
  - id: demo
    uri: lb://cleanarch-business-demo
    predicates:
      - Path=/demo/**
  - id: ssoclient1
    uri: lb://cleanarch-business-ssoclient1
    predicates:
      - Path=/ssoclient1/**
  - id: ssoclient2
    uri: lb://cleanarch-business-ssoclient2
    predicates:
      - Path=/ssoclient2/**