spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
      scg:
        order: -100
      datasource:
        # 名称随意
        api:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}-gateway-api-rules
            groupId: SENTINEL_GROUP
            namespace: sentinel-dev
            rule-type: gw-api-group
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}-gateway-flow-rules
            groupId: SENTINEL_GROUP
            namespace: sentinel-dev
            rule-type: gw-flow
      eager: true
      filter:
        enabled: false
  redis:
    host: 127.0.0.1
    password: 123456
#  r2dbc:
#    url: r2dbc:mysql://127.0.0.1:3306/sys?serverTimezone=GMT&characterEncoding=UTF-8
#    username: root
#    password: root
#    pool:
#      validation-query: SELECT 1
#      enabled: true
feign:
  httpclient:
    enabled: true
    #最大连接数
    max‐connections: 200
    #为每个url请求设置最大连接数
    max‐connections‐per‐route: 50
  client:
    config:
      default:
        # 以feign的超时时间为主
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full