spring:
  redis:
    host: localhost
    password:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
management:
  endpoints:
    web:
      exposure:
        include: ['*']
  endpoint:
    health:
      show-details: always
swagger:
  title: Platform Swagger API
  version: 1.0.0
  description: API
  license: Powered By Platform
  licenseUrl: https://blog.dlihaifeng.com/
  terms-of-service-url: https://blog.dlihaifeng.com/
  contact:
    name: 李海峰，徐航
    email: li7hai26@gmail.com
    url: https://blog.dlihaifeng.cn
  authorization:
    name: Platform OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://${GATEWAY-HOST:localhost}:${GATEWAY-PORT:8000}/auth/oauth/token
security:
  oauth2:
    client:
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
    resource:
      loadBalanced: true
      token-info-uri: http://application-auth/oauth/check_token
mybatis-plus:
  mapper-locations: classpath*:mybatis.mapper/*.xml