spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
management:
  endpoints:
    web:
      exposure:
        include: ['*']
  endpoint:
    health:
      show-details: always
swagger:
  title: Platform Swagger API
  version: 1.0.0
  description: API
  license: Powered By Platform
  licenseUrl: https://blog.dlihaifeng.com/
  terms-of-service-url: https://blog.dlihaifeng.com/
  contact:
    name: 李海峰，徐航
    email: li7hai26@gmail.com
    url: https://blog.dlihaifeng.cn
  authorization:
    name: Platform OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://${GATEWAY-HOST:localhost}:${GATEWAY-PORT:8000}/auth/oauth/token
mybatis-plus:
  mapper-locations: classpath*:mybatis.mapper/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl