spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
management:
  endpoints:
    web:
      exposure:
        include: ['*']
  endpoint:
    health:
      show-details: always

mybatis-plus:
  mapper-locations: classpath*:mybatis.mapper/*.xml
  typeAliasesPackage: com.github.jgzl.**.entity;com.github.jgzl.**.typehandler
  typeEnumsPackage: com.github.jgzl.**.enums
  global-config:
    db-config:
      id-type: auto
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
  compression:
    request:
      enabled: true
    response:
      enabled: true

oss:
  path-style-access: false
  endpoint: localhost:9000
  access-key: cleanarch
  secret-key: cleanarch
  bucketName: cleanarch
