server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: ['*']
  endpoint:
    health:
      show-details: always
spring:
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://api.192.168.0.232.nip.io/oauth/login/
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1