spring:
  cloud:
    gateway:
      default-filters:
      routes:
        - id: cpa-demo
          uri: lb://application-demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        - id: cpa-template-dubbo-web
          uri: lb://application-template-dubbo-service-web
          predicates:
            - Path=/dubbo/**
          filters:
            - StripPrefix=1