spring:
  cloud:
    gateway:
      default-filters:
      routes:
        - id: auth
          uri: lb://application-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: upms
          uri: lb://application-upms
          predicates:
            - Path=/upms/**
          filters:
            - StripPrefix=1
        - id: demo
          uri: lb://application-demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        - id: dubbo
          uri: lb://application-template-dubbo-service-web
          predicates:
            - Path=/dubbo/**
          filters:
            - StripPrefix=1
        - id: openfeign
          uri: lb://application-template-openfeign
          predicates:
            - Path=/openfeign/**
          filters:
            - StripPrefix=1