spring:
  cloud:
    gateway:
      default-filters:
      routes:
        - id: cpa-demo
          uri: lb://application-demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1