server:
  port: 8030
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform-core?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
  redis:
    host: localhost
    password:
  thymeleaf:
    cache: false
security:
  oauth2:
    client:
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
# 应用启动时饥饿加载ribbon客户端负载均衡，第一次调用时间过长
ribbon:
  eager-load:
    enabled: true
    clients: application-upms,application-codegen
logging:
  level:
    com.gitee.common.upms: debug