#主从读写分离配置
server:
  port: 8040
spring:
  freemarker:
    cache: false
    request-context-attribute: request
  shardingsphere:
    dataSource:
      ds-master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/odb?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT&allowPublicKeyRetrieval=true
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      ds-slave0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/odb?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT&allowPublicKeyRetrieval=true
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      ds-slave1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/odb?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT&allowPublicKeyRetrieval=true
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      names: ds-master,ds-slave0,ds-slave1
    props:
      sql:
        show: true
    masterslave:
      name: ms
      master-data-source-name: ds-master
      slave-data-source-names: ds-slave0,ds-slave1
  redis:
    host: 192.168.0.5
    password:
redis:
  topic:
    chat: chat-topic
security:
  oauth2:
    client:
      # 客户端ID
      client-id: app
      # 客户端密钥
      client-secret: app
      # 获取访问令牌的URI
      access-token-uri: http://localhost:8030/oauth/token
      # 用户将被重定向到的授权 URI
      user-authorization-uri: http://localhost:8030/oauth/authorize
    resource:
      jwt:
        # 获取JWT 非对称加密的公钥URI
        key-uri: http://localhost:8030/oauth/token_key
sso:
  oauth2:
    url-permit-all:
      - /actuator/**
      - /v2/api-docs
      - /webjars/**
      - /static/**
      - /**/*.css
      - /**/*.jpg
      - /**/*.jpeg
      - /**/*.png
      - /**/*.svg
      - /**/*.woff2
      - /**/*.js
      - /**/*.ico