server:
  port: 8032
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform-core?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
  redis:
    host: localhost
    password:
security:
  oauth2:
    client:
      client_id: app
      client_secret: app
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
    resource:
      loadBalanced: true
      token-info-uri: http://gateway-scg/auth/oauth/check_token