USE odb7;
CREATE TABLE o_order0 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order1 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE `o_dict` (
	`id` BIGINT ( 20 ) NOT NULL,
	`shop_id` BIGINT ( 20 ) NULL DEFAULT NULL,
	`key` VARCHAR ( 200 ) CHARACTER
	SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE
) ENGINE = INNODB CHARACTER
SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
CREATE TABLE o_order_item0 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order_item1 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
PRIMARY KEY ( id )
);
USE odb6;
CREATE TABLE o_order0 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order1 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE `o_dict` (
	`id` BIGINT ( 20 ) NOT NULL,
	`shop_id` BIGINT ( 20 ) NULL DEFAULT NULL,
	`key` VARCHAR ( 200 ) CHARACTER
	SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE
) ENGINE = INNODB CHARACTER
SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
CREATE TABLE o_order_item0 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order_item1 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
PRIMARY KEY ( id )
);
USE odb5;
CREATE TABLE o_order0 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order1 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE `o_dict` (
	`id` BIGINT ( 20 ) NOT NULL,
	`shop_id` BIGINT ( 20 ) NULL DEFAULT NULL,
	`key` VARCHAR ( 200 ) CHARACTER
	SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE
) ENGINE = INNODB CHARACTER
SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
CREATE TABLE o_order_item0 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order_item1 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
PRIMARY KEY ( id )
);
USE odb4;
CREATE TABLE o_order0 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order1 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE `o_dict` (
	`id` BIGINT ( 20 ) NOT NULL,
	`shop_id` BIGINT ( 20 ) NULL DEFAULT NULL,
	`key` VARCHAR ( 200 ) CHARACTER
	SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE
) ENGINE = INNODB CHARACTER
SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
CREATE TABLE o_order_item0 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order_item1 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
PRIMARY KEY ( id )
);
USE odb3;
CREATE TABLE o_order0 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order1 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE `o_dict` (
	`id` BIGINT ( 20 ) NOT NULL,
	`shop_id` BIGINT ( 20 ) NULL DEFAULT NULL,
	`key` VARCHAR ( 200 ) CHARACTER
	SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE
) ENGINE = INNODB CHARACTER
SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
CREATE TABLE o_order_item0 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order_item1 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
PRIMARY KEY ( id )
);
USE odb2;
CREATE TABLE o_order0 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order1 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE `o_dict` (
	`id` BIGINT ( 20 ) NOT NULL,
	`shop_id` BIGINT ( 20 ) NULL DEFAULT NULL,
	`key` VARCHAR ( 200 ) CHARACTER
	SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE
) ENGINE = INNODB CHARACTER
SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
CREATE TABLE o_order_item0 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order_item1 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
PRIMARY KEY ( id )
);
USE odb1;
CREATE TABLE o_order0 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order1 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE `o_dict` (
	`id` BIGINT ( 20 ) NOT NULL,
	`shop_id` BIGINT ( 20 ) NULL DEFAULT NULL,
	`key` VARCHAR ( 200 ) CHARACTER
	SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE
) ENGINE = INNODB CHARACTER
SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
CREATE TABLE o_order_item0 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order_item1 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
PRIMARY KEY ( id )
);
USE odb0;
CREATE TABLE o_order0 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order1 (
	id BIGINT AUTO_INCREMENT,
	shop_id BIGINT NOT NULL,
	CODE VARCHAR ( 50 ),
	create_time TIMESTAMP ( 0 ),
	PRIMARY KEY ( id )
);
CREATE TABLE `o_dict` (
	`id` BIGINT ( 20 ) NOT NULL,
	`shop_id` BIGINT ( 20 ) NULL DEFAULT NULL,
	`key` VARCHAR ( 200 ) CHARACTER
	SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE
) ENGINE = INNODB CHARACTER
SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
CREATE TABLE o_order_item0 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
	PRIMARY KEY ( id )
);
CREATE TABLE o_order_item1 (
	id BIGINT AUTO_INCREMENT,
	order_id BIGINT,
	shop_id BIGINT NOT NULL,
	NAME VARCHAR ( 50 ),
PRIMARY KEY ( id )
);