server:
  port: 8089
spring:
  application:
    name: camunda
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/camunda?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: admin
    filter:
      create: All tasks