management:
  endpoints:
    web:
      exposure:
        include: ['*']
  endpoint:
    health:
      show-details: always
server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: remoteaddr_route
          uri: http://api.192.168.0.232.nip.io/oauth/login/
          predicates:
            - Path=/test/**
          #- Demo=/demo/**
          filters:
            - Customer=true
            - StripPrefix=1